### PR TITLE
Fix TypeScript types for `set` method

### PR DESCRIPTION
**Pull request by notlmn**
From https://github.com/bfred-it/webext-options-sync/commit/fc77d661742e95ecefce66d0b738c1e3a7d7aae3#r34067329.

Fixes [Travis build](https://travis-ci.org/sindresorhus/refined-github/jobs/550317445#L319) over at https://github.com/sindresorhus/refined-github/pull/2146.

### CODE REVIEW

**Comment by notlmn** [comment]
Reverted dde242a cause I'm a complete TS noob and I failed to implement `RequireAtLeastOne` into this one trying multiple ways.

@bfred-it If `Partial` isn't enough for you, you are free to close this PR.

**Comment by bfred-it** [comment]
Oh the code was right, but `xo` can't find type-fest because of a bug. RGH solved it with https://github.com/sindresorhus/refined-github/blob/303b8feabcaae3b7636335647c28ea61463de0e7/package.json#L100

**Comment by notlmn** [comment]
I was getting other weird errors when using `RequireAtLeastOne`.

```
source/index.ts:281:12 - error TS2345: Argument of type 'TOptions' is not assignable to parameter of type 'RequireAtLeastOne<TOptions, keyof TOptions>'.
  Type 'Options' is not assignable to type 'RequireAtLeastOne<TOptions, keyof TOptions>'.
    Type 'Options' is not assignable to type 'Required<Pick<TOptions, keyof TOptions>>'.
      Type 'TOptions' is not assignable to type 'Required<Pick<TOptions, keyof TOptions>>'.
        Type 'Options' is not assignable to type 'Required<Pick<TOptions, keyof TOptions>>'.

281     this.set({[name]: value} as TOptions);
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by bfred-it** [comment]
They were both bugs, so I silenced them. I'm going to try them in RGH

**Comment by bfred-it** [comment]
I tried this and your PR compiles :tada:

**Comment by notlmn** [comment]
Yay!

Sorry I wasn't able to test this myself, I've been moving again and wasn't able to sit before a computer for long.

Glad this worked though (frankly, I need to learn more TS).

**Comment by bfred-it** [comment]
Trust me, I’m still fighting TS myself 😂 🥊

**Pull request merged**
