### PR TITLE
Convert to TypeScript

### PR DESCRIPTION
**Pull request by bfred-it**
cc @nickytonline if you wanna take a look. The API hasn't changed yet, but we have a chance to fix the type of `Options` now, as talked about in https://github.com/sindresorhus/refined-github/pull/1780#discussion_r285386329

Most I'd like to know if there's a way to pass `typeof defaults` through to the defaults — this may be easier once the constructor accepts `{defaults}`

> Problem to keep in mind: https://github.com/Microsoft/TypeScript/issues/5341

### CODE REVIEW

**Comment by nickytonline** [comment]
I'll take a look at this this weekend.

**Comment by nickytonline** [comment]
Looking at it, I think everywhere you have `OptionsSync.Options`, can be replaced by `T = OptionsSync.Options` and use `T` wherever `OptionsSync.Options` is used for types. I think this makes sense unless I'm missing something since anyone that consumes this package will have their own set of options. Happy to chat more about this whenever you're free.

e.g.

```javascript
getAll<T = OptionsSync.Options>(): Promise<T> {
   ...
}
```

**Comment by bfred-it** [comment]
Is there a way to have the types associated with the instance instead of having each method generic?

Also because `T` should always match `typeof Definitions.defaults`

**Comment by nickytonline** [comment]
I don't think you can get away without generics. I'd have to mess around with this a bit more once you're other branch is merged or up for review. Let me know when that is up or merged and I'll find some time to tinker.

**Comment by bfred-it** [comment]
It looks like I can have a generic class, so the instance will return T = defaults, instead of specifying the type in the getter setter

**Pull request merged**
