### PR TITLE
Validate inputs before saving them

### PR DESCRIPTION
**Pull request by ramlmn**
Solves #2.

### CODE REVIEW

**Comment by ramlmn** [comment]
Shouldn't we also specify this in README? Tell the developers to add error messages.

**Comment by bfred-it** [comment]
Sure, can you add a section under `Migrations` that explains this behavior and gives an HTML+CSS example?

**Comment by ramlmn** [comment]
Should I include that in this PR?

**Comment by bfred-it** [comment]
Either way works. I'll release a new version once the readme is in

**Comment by ramlmn** [comment]
Is this good enough?

**Comment by ramlmn** [comment]
I'm so bad at describing things! 😅

**Comment by bfred-it** [comment]
Don't worry, I'm just very picky with documentation :D

**Comment by bfred-it** [comment]
I had forgotten about this! Thanks a lot for your contributions! :)

**Pull request merged**
